### ISSUE TITLE
App crash 

### ISSUE THREAD

**Issue by islam2hamy** [CodeDead/DeadHash-android#27]
FATAL EXCEPTION: main
Process: com.codedead.deadhash, PID: 25557
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.codedead.deadhash/com.codedead.deadhash.gui.MainActivity}: android.view.InflateException: Binary XML file line #11: Binary XML file line #13: Error inflating class ImageView
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2723)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2784)
	at android.app.ActivityThread.-wrap12(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1523)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:163)
	at android.app.ActivityThread.main(ActivityThread.java:6238)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:933)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)
Caused by: android.view.InflateException: Binary XML file line #11: Binary XML file line #13: Error inflating class ImageView
Caused by: android.view.InflateException: Binary XML file line #13: Error inflating class ImageView
Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x7f0e0001
	at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:201)
	at android.content.res.MiuiResourcesImpl.getValue(MiuiResourcesImpl.java:95)
	at android.content.res.Resources.getValue(Resources.java:1308)
	at androidx.appcompat.widget.q0.f()
	at androidx.appcompat.widget.q0.k()
	at androidx.appcompat.widget.q0.j()
	at e.a.b()
	at androidx.appcompat.widget.q.g()
	at androidx.appcompat.widget.r.<init>()
	at androidx.appcompat.widget.r.<init>()
	at androidx.appcompat.app.h.i()
	at androidx.appcompat.app.h.r()
	at androidx.appcompat.app.g.V()
	at androidx.appcompat.app.g.onCreateView()
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:794)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:752)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:883)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:846)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:886)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:846)
	at android.view.LayoutInflater.parseInclude(LayoutInflater.java:1019)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:879)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:846)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:886)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:846)
	at android.view.LayoutInflater.parseInclude(LayoutInflater.java:1019)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:879)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:846)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:522)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:430)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:377)
	at androidx.appcompat.app.g.D()
	at androidx.appcompat.app.e.setContentView()
	at com.codedead.deadhash.gui.MainActivity.onCreate()
	at android.app.Activity.performCreate(Activity.java:6857)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2676)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2784)
	at android.app.ActivityThread.-wrap12(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1523)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:163)
	at android.app.ActivityThread.main(ActivityThread.java:6238)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:933)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)

**Comment by islam2hamy** [comment]
Android : 7.1.2
Miui 11.0.2

**Comment by CodeDead** [comment]
@islam2hamy Thanks for the bug report.

Did you install DeadHash from F-Droid or Google Play? Could you try the Google Play version if you have the F-Droid version installed to see if the problem is present there? It might be an issue with the build process on F-Droid.

If you're using the Google Play version, can you try and clear the cache of DeadHash and/or reinstall the application and see if the problem persists?

**Comment by islam2hamy** [comment]
Google Play version crash also

> @islam2hamy Thanks for the bug report.
> 
> Did you install DeadHash from F-Droid or Google Play? Could you try the Google Play version if you have the F-Droid version installed to see if the problem is present there? It might be an issue with the build process on F-Droid.

F-Droid

> If you're using the Google Play version, can you try and clear the cache of DeadHash and/or reinstall the application and see if the problem persists?

Google Play version crash also

**Comment by islam2hamy** [comment]
Yes 
Ameixa ,  kiss launcher

**Comment by CodeDead** [comment]
Custom icon packs could get bugged results from Android, best option is to disable the custom icon pack on older Android models that experience crashes.
